#!/usr/bin/env bash

sudo apt install curl
echo 'curl installed'

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash

# this part is needed to use nvm in this script since bashrc is not soured yet.
# bashrc can't be sourced since this not interactive 
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

nvm install node
nvm use --lts
echo 'nvm installed'

