#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
branch=""
dry="0"

while [[ $# > 0 ]]; do
    if [[ $1 == "--dry" ]]; then
        dry="1"
    else
        branch="$1"
    fi
    shift
done

log() {
    if [[ $dry == "1" ]]; then
        echo "[DRY_RUN]: $@"
    else
        echo "$@"
    fi
}

execute() {
    log "execute $@"
    if [[ $dry == "1" ]]; then
        return
    fi
    "$@"
}


if [ `git rev-parse --verify $branch 2>/dev/null` ]
then
   log 'branch already exists, exiting'
   execute git worktree add $branch $branch
   execute $script_dir/../syncPOD/sync_POD_from_root $branch
   exit 0
fi


execute git worktree add -b $branch $branch
execute $script_dir/../syncPOD/sync_POD_from_root $branch